## NumPy Tutorial

### NumPy
<b>NumPy is the fundamental package for scientific computing with Python. It contains among other things:
<br>>a powerful N-dimensional array object
<br>>sophisticated (broadcasting) functions
<br>>tools for integrating C/C++ and Fortran code
<br>>useful linear algebra, Fourier transform, and random number capabilities</b>
<br> Source:https://docs.scipy.org/doc/numpy/user/quickstart.html

In [1]:
import numpy as np

### Basic Numpy functions

In [2]:
a= np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
b=a.reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(b.shape)

(3, 5)


In [5]:
print(a.shape)# reshapes the array to 3 row and 5 column

(15,)


In [6]:
print(b.ndim)# Dimension of the array

2


In [7]:
a.dtype.name # prints the datatype

'int64'

In [8]:
b.size #prints the size of the array

15

### Creation of 1D and 2D arrays

In [9]:
c = np.array([6, 7, 8]) # creating array
print(c)

[6 7 8]


In [10]:
d = np.array([(1.5,2,3), (4,5,6)])
print(d)
d.dtype

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


dtype('float64')

In [11]:
d = np.array([(1.5,2,3), (4,5,6)],dtype="int64")
print(d)
d.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [12]:
d.T # transposing a matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
e=np.linspace( 0, 2, 9 ) # array with equal 9 intervals between 0,2
print(e)

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


## NumPy Operations

In [14]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [15]:
print(A+B)
print(np.add(A,B))# addition

[[3 1]
 [3 5]]
[[3 1]
 [3 5]]


In [16]:
np.sum(A,axis=0)#adding horizontal

array([1, 2])

In [17]:
np.sum(A,axis=1)# addinf vertical

array([2, 1])

In [18]:
print(A-B)
print(np.subtract(A,B))# subtraction

[[-1  1]
 [-3 -3]]
[[-1  1]
 [-3 -3]]


In [19]:
print(A*B)
print(np.multiply(A, B)) #Element wise Multiplication

[[2 0]
 [0 4]]
[[2 0]
 [0 4]]


In [20]:
print(A @ B)
print(A.dot(B))#Matrix Product

[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


## Indexing

In [21]:
a=np.array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [22]:
a[2]# element at position 2

8

In [23]:
a[2:5]# elemts frompos 2 till 5

array([ 8, 27, 64])

In [24]:
a[:]# all elemnts

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [25]:
a.size

10

In [26]:
b=a.reshape(2,5)
print(b)

[[  0   1   8  27  64]
 [125 216 343 512 729]]


In [27]:
b[1,1]# elemt at row 1 col 1

216

In [28]:
b[0,1:3]#elements in row 0 from columns 1 till pos 3

array([1, 8])